-- 20191212 NJ XENO-94 - init and created the table t:EMPPAYROLSUM
IF OBJECT_ID('XENO.EMPPAYROLSUM', 'U') IS NOT NULL
DROP TABLE XENO.EMPPAYROLSUM;
GO
CREATE TABLE XENO.EMPPAYROLSUM(
    CODE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	CMPNO VARCHAR (20) NOT NULL,
	EMPNO VARCHAR (20) NOT NULL,
	EPFNO VARCHAR (20) NOT NULL,
	EMPNAME VARCHAR (150) NOT NULL,
	BASICSAL DECIMAL (12,6) NOT NULL,
	NOTHRS DECIMAL (6,3) NULL,
	DOTHRS DECIMAL (6,3) NULL,
	NOTAMT DECIMAL (12,6) NULL,
	DOTAMT DECIMAL (12,6) NULL,
	NPDAYS DECIMAL (5,3) NULL,
	NPAMT DECIMAL (12,6) NULL,
	TOTALLO DECIMAL (12,6) NULL,
	TOTDEDU DECIMAL (12,6) NULL,
	PAYEE DECIMAL (12,6) NULL,
    CRTON DATETIME NOT NULL DEFAULT GETDATE(),
	CRTBY VARCHAR (30) NOT NULL DEFAULT 'TEST',
	MODON DATETIME NULL,
	MODBY VARCHAR (30) NULL
);

CREATE TABLE XENO.TOWN(
	CODE INT IDENTITY(1,1),
	NAME VARCHAR(30) NOT NULL,
	PROVINCE VARCHAR(30) NOT NULL,
	EXTENSION INT);

CREATE TABLE XENO.PROVINCE(
	CODE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	COUNTRYCODE INT NOT NULL,
	PHONECODE VARCHAR(3) NOT NULL,
	RELIGION VARCHAR(14)
	);

CREATE TABLE XENO.MULTIPLETABLES(
	CODE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NAME VARCHAR(20) NOT NULL,
	CRTON DATETIME NOT NULL DEFAULT GETDATE(),
	TOWN INT FOREIGN KEY REFERENCES XENO.TOWN(CODE),
	PROVINCE INT FOREIGN KEY REFERENCES XENO.PROVINCE(CODE)
	);

