
ALTER TABLE XENO.TESTDATA ADD CONSTRAINT PK_TESTDATA PRIMARY KEY(CODE);
ALTER TABLE XENO.TESTDATA ADD TOWN INT NOT NULL DEFAULT 0;
ALTER TABLE XENO.TESTDATA ADD CONSTRAINT FK_TOWM_XENO FOREIGN KEY(TOWN) REFERENCES XENO.TOWN(CODE);

ALTER TABLE XENO.TOWN ADD CONSTRAINT PK_TOWN PRIMARY KEY(CODE);